apiVersion: v1
kind: Service
metadata:
  name: flask-load-balancer-service 
spec:
  type: NodePort
  selector:
    app: flask-load-balancer
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080 
