apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-load-balancer
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: flask-load-balancer
  template:
    metadata:
      labels:
        app: flask-load-balancer
    spec:
      containers:
      - name: flask-load-balancer
        image: rushilsheth/load_balancer_lab:1.0.0
        ports:
        - containerPort: 8080
